### ISSUE TITLE
About books

### ISSUE THREAD

**Issue by sapegin** [miduga/ama#1]
* What are you reading now? 
* What do you usually read: tech or fiction?
* What are the last three books you like?

**Comment by miduga** [comment]
Thanks for asking! :) You're the first one!

- I'm reading Falcó of Arturo Pérez-Reverte, about spies and suspense. I think, right now, this is only available in Spanish.

- I usually read science-fiction books but because my work I tend to read technical books as well. I've to confess that I particularly like the zombies genre.

- Last three books I liked are:
* The Day of the Triffids
* The Shadow of the Wind
* The Martian

**Comment by sapegin** [comment]
Thanks! _The Shadow Of The Wind_ sounds interesting, spies too (but I couldn‘t find an English description of the book) ;-)
